### ISSUE TITLE
Browser crashes when you click '.' without a 0 first

### ISSUE THREAD

**Issue by petros789** [leosartaj/jquery.ss.calculator#1]
No console information is shown, it appears to immediately cause the browser tab to become unable to do anything else.

**Comment by leosartaj** [comment]
I checked it. It appears if dot is pressed first with length of output being 0, the code is getting stuck in an infinite loop. On some debugging, it is apparently due to a missing condition in the while loop in _dot function. It can be fixed by changing condition `--x` to say `x > 0 && --x`. If you want you can fix it. Thanks for pointing out. (y)

**Comment by petros789** [comment]
That was my conclusion as well for it, I just put up a pull request for a bugfix that worked for me if you'd like to use it.
